baseURL = "/"
languageCode = "en-us"
languageLang = "en"
title = "web://workbook"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[imaging]
quality = 75
