[build]
publish = "public"
command = "npm run build"

[context.production.environment]
HUGO_VERSION = "0.108.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "npm run deploy:preview"

[context.deploy-preview.environment]
HUGO_VERSION = "0.108.0"
