name: pr-title-linter

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-title-linter:
    uses: project-calavera/calavera-reusable-actions/.github/workflows/pr-title-linter.yml@main
    with:
      target-repo: "mechanical-ink/calavera-reusable-actions"
